/*
 * PLC_IO_GPIO.cpp
 *
 *  Created on: 17-May-2023
 *      Author: sanjay
 */

#include "main.h"
#include "string.h"
#include "stm32f3xx_hal_flash.h"


#include "serialComHandlerV2.h"
#include "PLC.h"



// inputs
#define NEDDLE_POS_SENSOR_GPIO GPIOB
#define NEDDLE_POS_SENSOR_PIN	GPIO_PIN_0

#define NEDDLE_TOP_SENSOR_GPIO GPIOB
#define NEDDLE_TOP_SENSOR_PIN	GPIO_PIN_1

#define NEEDLE_DOWN_SENSOR_GPIO	GPIOB
#define NEEDLE_DOWN_SENSOR_PIN	GPIO_PIN_2

#define NEEDLE_HOOK_POS_GPIO
#define NEEDLE_HOOK_POS_PIN


#define ZERO_SIG_GPIO GPIOC
#define ZERO_SIG_PIN	GPIO_PIN_4


//outputs
#define VFD_FWD_GPIO	GPIOC
#define VFD_M1_GPIO		GPIOA
#define VFD_M2_GPIO		GPIOA
#define VFD_M3_GPIO		GPIOA
#define VFD_M4_GPIO		GPIOA

#define VFD_FWD_PIN		GPIO_PIN_12
#define VFD_M1_PIN		GPIO_PIN_9
#define VFD_M2_PIN		GPIO_PIN_10
#define VFD_M3_PIN		GPIO_PIN_11
#define VFD_M4_PIN		GPIO_PIN_15

#define BREAK_GPIO	GPIOB
#define BREAK_PIN	GPIO_PIN_8


#define START_BUTTON_GPIO	GPIOC
#define START_BUTTON_PIN	GPIO_PIN_14

#define STOP_BUTTON_GPIO	GPIOC
#define STOP_BUTTON_PIN		GPIO_PIN_15

#define QUILT_SIG_GPIO		GPIOC
#define QUILT_SIG_PIN		GPIO_PIN_3

#define UNLATCH_QUILT_GPIO	GPIOB
#define UNLATCH_QUILT_PIN	GPIO_PIN_7

#define LATCH_QUILT_GPIO	GPIOB
#define LATCH_QUILT_PIN		GPIO_PIN_5

#define LOWER_THREAD_LOOSE_VALVE_GPIO	GPIOB
#define LOWER_THREAD_LOOSE_VALVE_PIN	GPIO_PIN_4

#define UPPER_THREAD_LOOSE_VALVE_GPIO	GPIOD
#define UPPER_THREAD_LOOSE_VALVE_PIN	GPIO_PIN_2

#define LOOPER_VALVE_GPIO			GPIOB
#define LOOPER_VALVE_PIN			GPIO_PIN_6









namespace PLC
{


const X_INPUT_t x_gpio[16] =
{
	{X0, ZERO_SIG_GPIO, ZERO_SIG_PIN},
	{X1, NEDDLE_TOP_SENSOR_GPIO, NEDDLE_TOP_SENSOR_PIN},
	{X2, NEDDLE_POS_SENSOR_GPIO, NEDDLE_POS_SENSOR_PIN},
	{X3, NEEDLE_DOWN_SENSOR_GPIO, NEEDLE_DOWN_SENSOR_PIN},

	{X4, START_BUTTON_GPIO, START_BUTTON_PIN},
	{X5, STOP_BUTTON_GPIO, STOP_BUTTON_PIN},

	{X6, QUILT_SIG_GPIO, QUILT_SIG_PIN},
	{X_NOPE, NULL, 0},
	{X_NOPE, NULL, 0},
	{X_NOPE, NULL, 0},
	{X_NOPE, NULL, 0},
	{X_NOPE, NULL, 0},
	{X_NOPE, NULL, 0},
	{X_NOPE, NULL, 0},
	{X_NOPE, NULL, 0},
	{X_NOPE, NULL, 0},
};






const Y_OUTPUT_t y_gpio[16] =
{
	{Y0, VFD_FWD_GPIO, VFD_FWD_PIN},
	{Y1, VFD_M1_GPIO, VFD_M1_PIN},
	{Y2, VFD_M2_GPIO, VFD_M2_PIN},
	{Y3, VFD_M3_GPIO, VFD_M3_PIN},
	{Y4, VFD_M4_GPIO, VFD_M4_PIN},
	{Y5, BREAK_GPIO, BREAK_PIN},

	{Y6, LOWER_THREAD_LOOSE_VALVE_GPIO, LOWER_THREAD_LOOSE_VALVE_PIN},
	{Y7, UPPER_THREAD_LOOSE_VALVE_GPIO, UPPER_THREAD_LOOSE_VALVE_PIN},
	{Y8, LOOPER_VALVE_GPIO, LOOPER_VALVE_PIN},

	{Y9, LATCH_QUILT_GPIO, LATCH_QUILT_PIN},
	{Y10, UNLATCH_QUILT_GPIO, UNLATCH_QUILT_PIN},
	{Y11, ULED_1_GPIO_Port, ULED_1_Pin},
	{Y12, ULED_2_GPIO_Port, ULED_2_Pin},
	{Y13, ULED_3_GPIO_Port, ULED_3_Pin},
	{Y_NOPE, NULL, 0},
	{Y_NOPE, NULL, 0},
};


}
